// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // DATABASE_URL: Neon Pooler-URL (für Laufzeit-Queries via @neondatabase/serverless)
    // DIRECT_URL: Neon direkte Verbindung (für Migrationen via prisma db push
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
